import { lazy } from "react";

export const AIChat = lazy(() => import("../pages/AIChat"));
export const Analytics = lazy(() => import("../pages/Analytics"));
export const CreatorScore = lazy(() => import("../pages/CreatorScore"));
export const Dashboard = lazy(() => import("../pages/Dashboard"));
export const Instagram = lazy(() => import("../pages/Instagram"));
export const InstagramCallback = lazy(() => import("../pages/InstagramCallback"));
export const Insights = lazy(() => import("../pages/Insights"));
export const Landing = lazy(() => import("../pages/Landing"));
export const Login = lazy(() => import("../pages/Login"));
export const NotFound = lazy(() => import("../pages/NotFound"));
export const Notes = lazy(() => import("../pages/Notes"));
export const Profile = lazy(() => import("../pages/Profile"));
export const Privacy = lazy(() => import("../pages/Privacy"));
export const ProductStory = lazy(() => import("../pages/ProductStory"));
export const Recommendations = lazy(() => import("../pages/Recommendations"));
export const Settings = lazy(() => import("../pages/Settings"));
export const Signup = lazy(() => import("../pages/Signup"));
export const Terms = lazy(() => import("../pages/Terms"));
export const VerifyEmail = lazy(() => import("../pages/VerifyEmail"));
