export const routePaths = {
  dashboard: "/dashboard",
  analytics: "/analytics",
  creatorScore: "/creator-score",
  insights: "/insights",
  recommendations: "/recommendations",
  creatorNews: "/creator-news",
  chat: "/ai-chat",
  notes: "/notes",
  instagram: "/instagram",
  instagramCallback: "/instagram/callback",
  settings: "/settings",
  profile: "/profile",
  landing: "/landing",
  product: "/product",
  login: "/login",
  register: "/register",
  signup: "/signup",
};
