export const AI_MODEL_CAPABILITIES = {
  TEXT: "text",
  VISION: "vision",
};

export const AI_MODEL_GROUPS = {
  FAST: "fast",
  BALANCED: "balanced",
  REASONING: "reasoning",
  CODING: "coding",
  VISION: "vision",
  FALLBACK: "fallback",
};

export const AI_MODELS = [
  {
    id: "openrouter/free",
    name: "OpenRouter Free Router",
    provider: "openrouter",
    capability: AI_MODEL_CAPABILITIES.TEXT,
    group: AI_MODEL_GROUPS.FAST,
    supportsVision: true,
    enabled: true,
    priority: 1,
    timeoutMs: 18000,
  },

  {
    id: "liquid/lfm-2.5-1.2b-instruct:free",
    name: "Liquid LFM 2.5 1.2B Instruct Free",
    provider: "liquid",
    capability: AI_MODEL_CAPABILITIES.TEXT,
    group: AI_MODEL_GROUPS.FAST,
    supportsVision: false,
    enabled: true,
    priority: 2,
    timeoutMs: 8000,
  },
  {
    id: "nvidia/nemotron-nano-9b-v2:free",
    name: "NVIDIA Nemotron Nano 9B V2 Free",
    provider: "nvidia",
    capability: AI_MODEL_CAPABILITIES.TEXT,
    group: AI_MODEL_GROUPS.FAST,
    supportsVision: false,
    enabled: true,
    priority: 3,
    timeoutMs: 9000,
  },
  {
    id: "openai/gpt-oss-20b:free",
    name: "GPT OSS 20B Free",
    provider: "openai",
    capability: AI_MODEL_CAPABILITIES.TEXT,
    group: AI_MODEL_GROUPS.FAST,
    supportsVision: false,
    enabled: true,
    priority: 4,
    timeoutMs: 10000,
  },
  {
    id: "z-ai/glm-4.5-air:free",
    name: "GLM 4.5 Air Free",
    provider: "z-ai",
    capability: AI_MODEL_CAPABILITIES.TEXT,
    group: AI_MODEL_GROUPS.FAST,
    supportsVision: false,
    enabled: true,
    priority: 5,
    timeoutMs: 11000,
  },

  {
    id: "meta-llama/llama-3.3-70b-instruct:free",
    name: "Llama 3.3 70B Instruct Free",
    provider: "meta",
    capability: AI_MODEL_CAPABILITIES.TEXT,
    group: AI_MODEL_GROUPS.BALANCED,
    supportsVision: false,
    enabled: true,
    priority: 6,
    timeoutMs: 13000,
  },
  {
    id: "qwen/qwen3-next-80b-a3b-instruct:free",
    name: "Qwen3 Next 80B A3B Instruct Free",
    provider: "qwen",
    capability: AI_MODEL_CAPABILITIES.TEXT,
    group: AI_MODEL_GROUPS.BALANCED,
    supportsVision: false,
    enabled: true,
    priority: 7,
    timeoutMs: 13000,
  },
  {
    id: "minimax/minimax-m2.5:free",
    name: "MiniMax M2.5 Free",
    provider: "minimax",
    capability: AI_MODEL_CAPABILITIES.TEXT,
    group: AI_MODEL_GROUPS.BALANCED,
    supportsVision: false,
    enabled: true,
    priority: 8,
    timeoutMs: 13000,
  },
  {
    id: "baidu/cobuddy:free",
    name: "Baidu Cobuddy Free",
    provider: "baidu",
    capability: AI_MODEL_CAPABILITIES.TEXT,
    group: AI_MODEL_GROUPS.BALANCED,
    supportsVision: false,
    enabled: true,
    priority: 9,
    timeoutMs: 13000,
  },
  {
    id: "moonshotai/kimi-k2:free",
    name: "Kimi K2 Free",
    provider: "moonshotai",
    capability: AI_MODEL_CAPABILITIES.TEXT,
    group: AI_MODEL_GROUPS.BALANCED,
    supportsVision: false,
    enabled: true,
    priority: 10,
    timeoutMs: 14000,
  },

  {
    id: "openai/gpt-oss-120b:free",
    name: "GPT OSS 120B Free",
    provider: "openai",
    capability: AI_MODEL_CAPABILITIES.TEXT,
    group: AI_MODEL_GROUPS.REASONING,
    supportsVision: false,
    enabled: true,
    priority: 11,
    timeoutMs: 16000,
  },
  {
    id: "nvidia/nemotron-3-super-120b-a12b:free",
    name: "NVIDIA Nemotron 3 Super 120B A12B Free",
    provider: "nvidia",
    capability: AI_MODEL_CAPABILITIES.TEXT,
    group: AI_MODEL_GROUPS.REASONING,
    supportsVision: false,
    enabled: true,
    priority: 12,
    timeoutMs: 16000,
  },
  {
    id: "nvidia/nemotron-3-nano-30b-a3b:free",
    name: "NVIDIA Nemotron 3 Nano 30B A3B Free",
    provider: "nvidia",
    capability: AI_MODEL_CAPABILITIES.TEXT,
    group: AI_MODEL_GROUPS.REASONING,
    supportsVision: false,
    enabled: true,
    priority: 13,
    timeoutMs: 15000,
  },
  {
    id: "liquid/lfm-2.5-1.2b-thinking:free",
    name: "Liquid LFM 2.5 1.2B Thinking Free",
    provider: "liquid",
    capability: AI_MODEL_CAPABILITIES.TEXT,
    group: AI_MODEL_GROUPS.REASONING,
    supportsVision: false,
    enabled: true,
    priority: 14,
    timeoutMs: 12000,
  },
  {
    id: "inclusionai/ring-2.6-1t:free",
    name: "inclusionAI Ring 2.6 1T Free",
    provider: "inclusionai",
    capability: AI_MODEL_CAPABILITIES.TEXT,
    group: AI_MODEL_GROUPS.REASONING,
    supportsVision: false,
    enabled: true,
    priority: 15,
    timeoutMs: 18000,
  },

  {
    id: "qwen/qwen3-coder:free",
    name: "Qwen3 Coder Free",
    provider: "qwen",
    capability: AI_MODEL_CAPABILITIES.TEXT,
    group: AI_MODEL_GROUPS.CODING,
    supportsVision: false,
    enabled: true,
    priority: 16,
    timeoutMs: 18000,
  },
  {
    id: "poolside/laguna-xs.2:free",
    name: "Poolside Laguna XS.2 Free",
    provider: "poolside",
    capability: AI_MODEL_CAPABILITIES.TEXT,
    group: AI_MODEL_GROUPS.CODING,
    supportsVision: false,
    enabled: true,
    priority: 17,
    timeoutMs: 14000,
  },
  {
    id: "poolside/laguna-m.1:free",
    name: "Poolside Laguna M.1 Free",
    provider: "poolside",
    capability: AI_MODEL_CAPABILITIES.TEXT,
    group: AI_MODEL_GROUPS.CODING,
    supportsVision: false,
    enabled: true,
    priority: 18,
    timeoutMs: 15000,
  },
  {
    id: "cognitivecomputations/dolphin-mistral-24b-venice-edition:free",
    name: "Dolphin Mistral 24B Venice Free",
    provider: "cognitivecomputations",
    capability: AI_MODEL_CAPABILITIES.TEXT,
    group: AI_MODEL_GROUPS.CODING,
    supportsVision: false,
    enabled: true,
    priority: 19,
    timeoutMs: 14000,
  },
  {
    id: "openrouter/auto",
    name: "OpenRouter Auto Router",
    provider: "openrouter",
    capability: AI_MODEL_CAPABILITIES.TEXT,
    group: AI_MODEL_GROUPS.FALLBACK,
    supportsVision: true,
    enabled: true,
    priority: 20,
    timeoutMs: 18000,
  },

  {
    id: "google/gemma-4-31b-it:free",
    name: "Gemma 4 31B IT Free",
    provider: "google",
    capability: AI_MODEL_CAPABILITIES.VISION,
    group: AI_MODEL_GROUPS.VISION,
    supportsVision: true,
    enabled: true,
    priority: 1,
    timeoutMs: 16000,
  },
  {
    id: "google/gemma-4-26b-a4b-it:free",
    name: "Gemma 4 26B A4B IT Free",
    provider: "google",
    capability: AI_MODEL_CAPABILITIES.VISION,
    group: AI_MODEL_GROUPS.VISION,
    supportsVision: true,
    enabled: true,
    priority: 2,
    timeoutMs: 16000,
  },
  {
    id: "nvidia/nemotron-nano-12b-v2-vl:free",
    name: "NVIDIA Nemotron Nano 12B V2 VL Free",
    provider: "nvidia",
    capability: AI_MODEL_CAPABILITIES.VISION,
    group: AI_MODEL_GROUPS.VISION,
    supportsVision: true,
    enabled: true,
    priority: 3,
    timeoutMs: 15000,
  },
  {
    id: "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free",
    name: "NVIDIA Nemotron 3 Nano Omni 30B A3B Reasoning Free",
    provider: "nvidia",
    capability: AI_MODEL_CAPABILITIES.VISION,
    group: AI_MODEL_GROUPS.VISION,
    supportsVision: true,
    enabled: true,
    priority: 4,
    timeoutMs: 17000,
  },
  {
    id: "baidu/qianfan-ocr-fast:free",
    name: "Baidu Qianfan OCR Fast Free",
    provider: "baidu",
    capability: AI_MODEL_CAPABILITIES.VISION,
    group: AI_MODEL_GROUPS.VISION,
    supportsVision: true,
    enabled: true,
    priority: 5,
    timeoutMs: 12000,
  },
];

export const AI_ROUTER_CONFIG = {
  maxModelsPerRequest: 5,
  failureThreshold: 2,
  circuitBreakerCooldownMs: 10 * 60 * 1000,
  defaultTimeoutMs: 12000,
};

export const getEnabledModels = () => {
  return AI_MODELS.filter((model) => model.enabled);
};

export const getTextModels = () => {
  return getEnabledModels().filter((model) => !model.supportsVision);
};

export const getVisionModels = () => {
  return getEnabledModels().filter((model) => model.supportsVision);
};

export const getCandidateModels = ({ needsVision = false } = {}) => {
  const candidates = needsVision ? getVisionModels() : getTextModels();

  return candidates.sort((a, b) => a.priority - b.priority);
};