import mongoose from "mongoose";

/**
 * --------------------------------------------------
 * Analytics Snapshot Schema
 * --------------------------------------------------
 *
 * Purpose:
 * Stores a point-in-time snapshot of an
 * connected Instagram account.
 *
 * Why snapshots?
 *
 * Instagram only gives current values.
 *
 * Example:
 *
 * Today:
 * Followers = 100
 *
 * Tomorrow:
 * Followers = 120
 *
 * Without snapshots:
 * We only know 120.
 *
 * With snapshots:
 * We know growth = +20.
 *
 * This becomes the foundation for:
 *
 * - Growth Charts
 * - Creator Score
 * - AI Insights
 * - Trend Detection
 * - Weekly Reports
 * - Monthly Reports
 *
 */

const analyticsSnapshotSchema =
  new mongoose.Schema(
    {
      /**
       * --------------------------------------------------
       * Account Reference
       * --------------------------------------------------
       */

      account: {
        type:
          mongoose.Schema.Types.ObjectId,

        ref: "InstagramAccount",

        required: true,

        index: true,
      },

      /**
       * --------------------------------------------------
       * Snapshot Timestamp
       * --------------------------------------------------
       */

      snapshotDate: {
        type: Date,

        required: true,

        default: Date.now,

        index: true,
      },

      /**
       * --------------------------------------------------
       * Audience Metrics
       * --------------------------------------------------
       */

      followers: {
        type: Number,

        default: 0,

        min: 0,
      },

      following: {
        type: Number,

        default: 0,

        min: 0,
      },

      /**
       * --------------------------------------------------
       * Content Metrics
       * --------------------------------------------------
       */

      mediaCount: {
        type: Number,

        default: 0,

        min: 0,
      },

      /**
       * --------------------------------------------------
       * Engagement Metrics
       * --------------------------------------------------
       */

      totalLikes: {
        type: Number,

        default: 0,

        min: 0,
      },

      totalComments: {
        type: Number,

        default: 0,

        min: 0,
      },

      totalEngagement: {
        type: Number,

        default: 0,

        min: 0,
      },

      averageLikes: {
        type: Number,

        default: 0,

        min: 0,
      },

      averageComments: {
        type: Number,

        default: 0,

        min: 0,
      },

      averageEngagement: {
        type: Number,

        default: 0,

        min: 0,
      },

      /**
       * --------------------------------------------------
       * Growth Metrics
       * --------------------------------------------------
       *
       * Calculated during sync.
       */

      followerGrowth: {
        type: Number,

        default: 0,
      },

      engagementGrowth: {
        type: Number,

        default: 0,
      },

      mediaGrowth: {
        type: Number,

        default: 0,
      },

      /**
       * --------------------------------------------------
       * Creator Score
       * --------------------------------------------------
       *
       * Generated by scoring engine.
       */

      creatorScore: {
        type: Number,

        default: 0,

        min: 0,

        max: 100,
      },

      /**
       * --------------------------------------------------
       * Additional Metadata
       * --------------------------------------------------
       */

      metadata: {
        type: mongoose.Schema.Types.Mixed,

        default: {},
      },
    },
    {
      timestamps: true,
    }
  );

/**
 * --------------------------------------------------
 * Compound Indexes
 * --------------------------------------------------
 */

/**
 * Fast timeline queries
 */

analyticsSnapshotSchema.index({
  account: 1,
  snapshotDate: -1,
});

/**
 * Creator score history
 */

analyticsSnapshotSchema.index({
  account: 1,
  creatorScore: -1,
});

/**
 * --------------------------------------------------
 * JSON Transform
 * --------------------------------------------------
 */

analyticsSnapshotSchema.set(
  "toJSON",
  {
    transform: (_, ret) => {
      delete ret.__v;

      return ret;
    },
  }
);

/**
 * --------------------------------------------------
 * Model
 * --------------------------------------------------
 */

const AnalyticsSnapshot =
  mongoose.model(
    "AnalyticsSnapshot",
    analyticsSnapshotSchema
  );

export default AnalyticsSnapshot;